### ISSUE TITLE
Difference Schrijfrechten vs. Wijzigen status melding

### ISSUE THREAD

**Issue by erikveerm** [Signalen/frontend#27]
What is the difference between the roles _Schrijfrechten algemeen_ and   _Wijzigen status melding_? Being able to change the status of a notification is part of the basic functionality?

**Comment by bartjkdp** [comment]
In order to have enough permissions to change a status a user needs to have both _Schrijfrechten algemeen_ and _Wijzigen status melding_.

The user also needs to have the basic write access and the specific permission for:

- Create a signal (melding)
- Creating a note
- Changing the category

Reference: https://github.com/Signalen/backend/blob/73bd07562bd439d9a614c880d2f79653b602f5b2/api/app/signals/apps/api/generics/permissions.py#L84
