### ISSUE TITLE
Configurable signal city district (stadsdeel) filter options

### ISSUE THREAD

**Issue by jaccobrouwer** [Signalen/frontend#45]
## City districts

The city districts (stadsdelen) are currently hardcoded in the frontend.

The suggestion is to use the `areas` endpoint to fetch the city districts from the backend, passing `type_code=stadsdeel`, which will return city districts like this:

    {
      "name": "Zuidoost",
      "code": "03630000000016",
      "type": {
        "name": "stadsdeel",
        "code": "stadsdeel"
      },
      "bbox": [
        4.929328206539815,
        52.27817420103722,
        5.021543196706216,
        52.33115995017073
      ]
    }

The combination of `code` and `type.code` uniquely identifies an area.

## Filtering incidents

To filter incidents on a city district, currently, a letter is passed to the `signals` endpoint. The letter representing a city district is hardcoded in the frontend.

The suggestion is to use the `code` and `type.code` from the area combined to pass to the `signals` endpoint for filtering on a city district, like `area=stadsdeel:03630000000016`. This will, obviously, require changes in the backend as well.

Another change on the backend side is how an incident is returned from the `signals` endpoint. Now there is a `location.stadsdeel` property that contains the hard coded letter standing for a specific Amsterdam stadsdeel. This should become `location.district` containing the `code` of an area with `type.code` being `stadsdeel`.

Back-end requires the following changes:
- Location model needs area_type, area_code attribute
- Signals list end point must offer filtering on area_type and area_code
- When creating a signal, the area_type and area_code needs to be filled (check update location flow)

**Comment by boris-arkenaar** [comment]
**As an** administrator
**I want** to be able to configure the city districts (stadsdelen) and the
possible sources of incidents (bronnen)
**so** that I can filter incidents in the back office based on the city
districts and sources needed for my organization and city

## Current implementation

### Front office

#### City district

The backend will link an incident to a city district. For Amsterdam, the
available districts are fetched from a separate service.

#### Source, priority and type

When logged in, there are a few extra fields in the first step of the incident
form. These are the source, priority, and type of an incident. The possible
values for these fields are hardcoded in the frontend.

### Back office

In the back office, you can filter the list of incidents based on various
properties. These are:

- Status
- City district (stadsdeel)
- Priority (urgentie)
- Type
- Contact details 
- Feedback
- Source (bron)
- Category (categorie)

The possible categories are already fetched from the backend. All the others
are hardcoded in the frontend.

## Proposal

We would like all possible filter values to be defined in the backend. This
makes the application more flexible and makes it easier to update values later
on. This will also allow for configuring these values in the back office
itself.

Only one endpoint to fetch all filter values at once would be most convenient
and performant.

### Backend

We would like to extend the backend with a model for each type of filter. The
following filters can all have the same properties.

**Filters**

- Priority
- Type
- Contact
- Feedback
- Source
- Category

**Properties**

- Key, CharField
- Value, CharField
- Info, CharField

We need to give more attention to *Status* and *City district*.

*Status* has a *Warning* property instead of *Info*. We could refactor to
make use of *Info* for *Status* as well. There is also a *Color* attribute.
Where is that being used in the frontend? Then there are three different
collections of the statuses: *statusList*, *changeStatusOptionList* and
*defaultTextsOptionList*. How are we going to handle these?

For filtering in the frontend of city districts only *Key* and *Value*
properties are used. How are we going to store them in the backend, however,
where they are also needed to categorize incoming incidents?

We add a new endpoint to the API that allows fetching all filters:

`/signals/v1/public/filters`

The response looks as follows:

```json
{
  "_links": {},
  "count": 1,
  "results": {
    "category": [
      {
        "key": "category",
        "value": "Category"
      },
      { "key": "..." }
    ],
    "cityDistrict": [
      {
        "key": "cityDistrict",
        "value": "City district"
      },
      { "key": "..." }
    ],
    "contactDetails" : [
      {
        "key": "contactDetails",
        "value": "Contact details"
      },
      { "key": "..." }
    ],
    "feedback": [
      {
        "key": "feedback",
        "value": "Feedback"
      },
      { "key": "..." }
    ],
    "priority": [
      {
        "key": "priority",
        "value": "Priority"
      },
      { "key": "..." }
    ],
    "source": [
      {
        "key": "source",
        "value": "Source"
      },
      { "key": "..." }
    ],
    "status": [
      {
        "key": "status",
        "value": "Status"
      },
      { "key": "..." }
    ],
    "type": [
      {
        "key": "type",
        "value": "Type"
      },
      { "key": "..." }
    ]
  }
}
```

### Frontend

We need to implement a new call to fetch the filters from the backend. Since
the filters are needed in the incident form in the front office when logged
in, we should fetch the filters upon loading of the application, but only if
authorized. Somewhere the authorization is managed might be a good spot for
fetching the filters?

It would be nice if we could have the filters available without the need for a
fetch call. In the same way as we have all settings available, injected into
the `index.html`. But we think that's better saved for a second iteration.

## Migration path

1. We introduce the new endpoint in the API.
1. We load the currently hardcoded settings by manually creating a migration
   file based on the latest frontend code.
1. We load this data with `python manage.py loaddata`.
1. We introduce the change in the frontend.

## Admin

In the initial version, filters are configurable using the Django admin.

**Comment by felixfaassen** [comment]
Hi everyone. Nice to meet you all in the signalen dev call. I do not know if this is relevant to this issue.  Just for your consideration. When refering to geographical locations in data please consider https://tools.ietf.org/html/rfc7946 (GeoJSON) for describing data. If you want to refer to street names, postal codes you can also consider looking at https://www.mapcode.com/ which is an open standard for referring to locations and works globally. This way you do not have to refer to national data sources such as kadaster which helps make the code more scalable. I understand this may not be relevant now or does not have  a priority ;-) Just something I wanted to share.

**Comment by bartjkdp** [comment]
@felixfaassen thanks for the suggestion. GeoJSON is used in several places of the API.

**Comment by boris-arkenaar** [comment]
## City districts

The city districts (stadsdelen) are currently hardcoded in the frontend.

The suggestion is to use the `areas` endpoint to fetch the city districts from the backend, passing `type_code=stadsdeel`, which will return city districts like this:

    {
      "name": "Zuidoost",
      "code": "03630000000016",
      "type": {
        "name": "stadsdeel",
        "code": "stadsdeel"
      },
      "bbox": [
        4.929328206539815,
        52.27817420103722,
        5.021543196706216,
        52.33115995017073
      ]
    }

The combination of `code` and `type.code` uniquely identifies an area.

## Filtering incidents

To filter incidents on a city district, currently, a letter is passed to the `signals` endpoint. The letter representing a city district is hardcoded in the frontend.

The suggestion is to use the `code` and `type.code` from the area to pass to the `signals` endpoint for filtering on a city district, like `code=03630000000016&type_code=stadsdeel`. This will, obviously, require changes in the backend as well.

**Comment by felixfaassen** [comment]
> @felixfaassen thanks for the suggestion. GeoJSON is used in several places of the API. Areas are already configurable for specific implementations in the database, so using Kadaster areas in Signalen is optional.

Hi @bartjkdp thank you for yor response great to hear you are using geojson. 

To other thing I was mentioning is when you need refer to street names, postal codes. Please consider looking at https://www.mapcode.com/ which is an open standard for referring to locations and works globally. So instead of hardcoding streetnames or postal codes you can use mapcodes which will work any where in the world even when locations do not have zipcodes or street numbers. This way you do not have to refer to national data sources such as kadaster which helps make the code more scalable. 

Other major advantage is that you do not need to rely on 3rd party (reverse) geocoding services if you need to convert between coordinates and addresses or vice versa.

 I know the original developers of mapcode so if you need any help or want to know more about that I can hook you up. Great project I look forward to learn more about Signalen and everyone in the team working on it.

**Comment by boris-arkenaar** [comment]
Another similar project to refer to locations worldwide I find interesting is: https://what3words.com/about-us/

**Comment by felixfaassen** [comment]
> Another similar project to refer to locations worldwide I find interesting is: https://what3words.com/about-us/

@boris-arkenaar interesting thanks for sharing. Always nice to learn new technologies ;-) . Please note that what3words is not open source. That might be something for you and the team to consider when implementing. Good luck!

**Comment by CBuiVNG** [comment]
Back-end requires the following changes:
- Location model needs area_type, area_code attribute
- Area list end point must offer filtering on area_type and area_code
- When creating a signal, the area_type and area_code needs to be filled (check update location flow)

**Comment by boris-arkenaar** [comment]
@CBuiVNG With area list endpoint, you mean the `signals` endpoint?

**Comment by CBuiVNG** [comment]
> @CBuiVNG With area list endpoint, you mean the `signals` endpoint?

oops my bad, yes signals endpoint
